---
# Here you can add variables that will be available for all hosts.
region: northeurope
resource_group: BTH-kmom01-JAEI18-16a0e3
domain_name: epixor.me

root_user: azureuser

vmtags:
    StudentId: "jaei18"

pub_ssh_key_location: "~/.ssh/ansible.pem.pub"
